[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate — MUST match Serial.begin() in your code
monitor_speed = 115200

; Upload speed — faster upload to the board
upload_speed = 921600

; Serial monitor: echo what you type so you can see your own commands
monitor_echo = true

; Serial monitor: send data when you press Enter (not character by character)
monitor_filters = send_on_enter

; Libraries — add dependencies here (no manual downloads!)
lib_deps =
    robtillaart/AS5600@^0.6.1
    mathieucarbou/AsyncTCP @ ^3.3.2
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0